const ciclos = [
{nombre:"1er Ciclo", cursos:[
["MATEMÁTICA I",["NIVELACIÓN DE MATEMÁTICA"]],
["INTRODUCCIÓN A LA VIDA UNIVERSITARIA",[]],
["LABORATORIO DE QUÍMICA GENERAL",[]],
["QUÍMICA GENERAL",[]],
["INDIVIDUO Y MEDIO AMBIENTE",["NIVELACIÓN DE REDACCIÓN"]],
["INGLÉS I",[]],
["COMPRENSIÓN Y REDACCIÓN DE TEXTOS I",["NIVELACIÓN DE REDACCIÓN"]]
]},
{nombre:"2do Ciclo", cursos:[
["MATEMÁTICA II",["MATEMÁTICA I"]],
["CIUDADANÍA Y REFLEXIÓN ÉTICA",[]],
["INGLÉS II",["INGLÉS I"]],
["COMPRENSIÓN Y REDACCIÓN DE TEXTOS II",["COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"]],
["ESTADÍSTICA DESCRIPTIVA Y PROBABILIDADES",["MATEMÁTICA I"]],
["PRINCIPIOS DE ALGORITMOS",[]],
["DIBUJO PARA INGENIERÍA",["MATEMÁTICA I","INTRODUCCIÓN A LA VIDA UNIVERSITARIA"]]
]},
{nombre:"3er Ciclo", cursos:[
["LABORATORIO DE MECÁNICA CLÁSICA",["MATEMÁTICA II"]],
["MECÁNICA CLÁSICA",["MATEMÁTICA II"]],
["CÁLCULO I",["MATEMÁTICA II"]],
["INVESTIGACIÓN ACADÉMICA",["INDIVIDUO Y MEDIO AMBIENTE","COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"]],
["GEOLOGÍA",["DIBUJO PARA INGENIERÍA"]],
["PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN",["DIBUJO PARA INGENIERÍA"]],
["INGLÉS III",["INGLÉS II"]],
["PROBLEMAS Y DESAFÍOS EN EL PERÚ ACTUAL",["INDIVIDUO Y MEDIO AMBIENTE","COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"]]
]},
{nombre:"4to Ciclo", cursos:[
["LABORATORIO DE MATERIALES DE CONSTRUCCIÓN",["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"]],
["MATERIALES DE CONSTRUCCIÓN",["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"]],
["FLUIDOS Y TERMODINÁMICA",["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"]],
["LABORATORIO DE FLUIDOS Y TERMODINÁMICA",["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"]],
["CÁLCULO II",["CÁLCULO I"]],
["TOPOGRAFÍA - INGENIERÍA CIVIL",["ESTADÍSTICA DESCRIPTIVA Y PROBABILIDADES","PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN"]],
["ESTÁTICA",["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"]],
["INGLÉS IV",["INGLÉS III"]]
]},
{nombre:"5to Ciclo", cursos:[
["CONSTRUCCIÓN",["MATERIALES DE CONSTRUCCIÓN","PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN"]],
["FUNDAMENTOS DE DINÁMICA",["ESTÁTICA"]],
["GEOMÁTICA",["GEOLOGÍA","TOPOGRAFÍA - INGENIERÍA CIVIL"]],
["TECNOLOGÍA DEL CONCRETO",["MATERIALES DE CONSTRUCCIÓN"]],
["CÁLCULO AVANZADO PARA INGENIERÍA",["CÁLCULO II"]],
["CALCULO PARA LA TOMA DE DECISIONES",["CÁLCULO II"]],
["HERRAMIENTAS INFORMÁTICAS PARA LA TOMA DE DECISIONES",[]]
]},
{nombre:"6to Ciclo", cursos:[
["LABORATORIO DE ELASTICIDAD Y RESISTENCIA DE MATERIALES",["CÁLCULO AVANZADO PARA INGENIERÍA","CALCULO PARA LA TOMA DE DECISIONES","FUNDAMENTOS DE DINÁMICA"]],
["ELASTICIDAD Y RESISTENCIA DE MATERIALES",["CÁLCULO AVANZADO PARA INGENIERÍA","CALCULO PARA LA TOMA DE DECISIONES","FUNDAMENTOS DE DINÁMICA"]],
["LABORATORIO DE MECÁNICA DE FLUIDOS",["FUNDAMENTOS DE DINÁMICA"]],
["MECÁNICA DE FLUIDOS",["FUNDAMENTOS DE DINÁMICA"]],
["HERRAMIENTAS PARA LA COMUNICACIÓN EFECTIVA",["INVESTIGACIÓN ACADÉMICA"]],
["CONSTRUCCIONES ESPECIALES",["CONSTRUCCIÓN"]],
["MECÁNICA DE SUELOS",["GEOMÁTICA","FUNDAMENTOS DE DINÁMICA"]],
["CURSO INTEGRADOR I - CIVIL",["TECNOLOGÍA DEL CONCRETO","CONSTRUCCIÓN","GEOMÁTICA"]]
]},
{nombre:"7mo Ciclo", cursos:[
["LABORATORIO DE HIDRÁULICA DE CANALES",["CURSO INTEGRADOR I - CIVIL","MECÁNICA DE FLUIDOS"]],
["HIDRÁULICA DE CANALES",["CURSO INTEGRADOR I - CIVIL","MECÁNICA DE FLUIDOS"]],
["INGENIERÍA GEOTÉCNICA",["CURSO INTEGRADOR I - CIVIL","MECÁNICA DE SUELOS"]],
["MODELADO DE INFORMACIÓN DE EDIFICACIONES - BIM",["CONSTRUCCIONES ESPECIALES"]],
["INGENIERÍA DE CARRETERAS",["MECÁNICA DE SUELOS","GEOMÁTICA"]],
["INSTALACIONES EN EDIFICACIONES",["CONSTRUCCIONES ESPECIALES","MECÁNICA DE FLUIDOS"]],
["ANÁLISIS ESTRUCTURAL I",["ELASTICIDAD Y RESISTENCIA DE MATERIALES","CURSO INTEGRADOR I - CIVIL"]],
["FORMACIÓN PARA LA EMPLEABILIDAD",["HERRAMIENTAS PARA LA COMUNICACIÓN EFECTIVA"]]
]},
{nombre:"8vo Ciclo", cursos:[
["ANÁLISIS ESTRUCTURAL II",["ANÁLISIS ESTRUCTURAL I"]],
["HIDROLOGÍA APLICADA",["HIDRÁULICA DE CANALES"]],
["SEMINARIO DE INGENIERÍA CIVIL",["ANÁLISIS ESTRUCTURAL I","HIDRÁULICA DE CANALES","INGENIERÍA GEOTÉCNICA"]],
["MECÁNICA DE SUELOS APLICADA",["INGENIERÍA GEOTÉCNICA"]],
["ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA",["INSTALACIONES EN EDIFICACIONES"]],
["ADMINISTRACIÓN Y ORGANIZACIÓN DE EMPRESAS CONSTRUCTORAS",["INSTALACIONES EN EDIFICACIONES","MODELADO DE INFORMACIÓN DE EDIFICACIONES - BIM"]],
["CONSTRUCCIÓN DE CARRETERAS",["INGENIERÍA DE CARRETERAS"]],
["ÉTICA PROFESIONAL",["HERRAMIENTAS INFORMÁTICAS PARA LA TOMA DE DECISIONES","FORMACIÓN PARA LA EMPLEABILIDAD"]]
]},
{nombre:"9no Ciclo", cursos:[
["GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN",["ADMINISTRACIÓN Y ORGANIZACIÓN DE EMPRESAS CONSTRUCTORAS","ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA"]],
["INGENIERÍA DE CIMENTACIONES",["MECÁNICA DE SUELOS APLICADA"]],
["PAVIMENTOS",["CONSTRUCCIÓN DE CARRETERAS","MECÁNICA DE SUELOS APLICADA"]],
["INGENIERÍA DE LOS RECURSOS HIDRÁULICOS",["HIDROLOGÍA APLICADA"]],
["SISTEMA INTEGRADO DE GESTIÓN EN LA CONSTRUCCIÓN",["ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA"]],
["FORMACIÓN PARA LA INVESTIGACIÓN - CIVIL",["SEMINARIO DE INGENIERÍA CIVIL"]],
["CONCRETO ARMADO",["ANÁLISIS ESTRUCTURAL II"]]
]},
{nombre:"10mo Ciclo", cursos:[
["INGENIERÍA SISMORRESISTENTE",["CONCRETO ARMADO","INGENIERÍA DE CIMENTACIONES"]],
["GESTIÓN DE PROYECTOS DE INVERSIÓN PÚBLICA",["GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"]],
["TALLER DE INVESTIGACIÓN - CIVIL",["FORMACIÓN PARA LA INVESTIGACIÓN - CIVIL"]],
["CURSO INTEGRADOR II - CIVIL",["CURSO INTEGRADOR I - CIVIL","INGENIERÍA DE CIMENTACIONES","GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"]],
["FUNDAMENTOS DE METODOLOGÍA VDC EN EDIFICACIONES",["MODELADO DE INFORMACIÓN DE EDIFICACIONES - BIM","GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"]],
["SEGURIDAD Y SALUD OCUPACIONAL EN OBRAS DE CONSTRUCCIÓN",["SISTEMA INTEGRADO DE GESTIÓN EN LA CONSTRUCCIÓN","GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"]],
["SOSTENIBILIDAD AMBIENTAL EN LA CONSTRUCCIÓN",["HIDROLOGÍA APLICADA"]],
["ANÁLISIS DE ESTRUCTURAS POR ELEMENTOS FINITOS",["CONCRETO ARMADO"]],
["MÉTODOS NUMÉRICOS",["CÁLCULO AVANZADO PARA INGENIERÍA"]],
["ELEMENTARY BUSINESS ENGLISH",["INGLÉS IV"]]
]}
];

const malla=document.getElementById("malla");
const barra=document.getElementById("barraGeneral");
const reset=document.getElementById("reset");
const modo=document.getElementById("modo");

let aprobados=new Set(JSON.parse(localStorage.getItem("aprobados")||"[]"));

function render(){
malla.innerHTML="";
let total=0;

ciclos.forEach(c=>{
const box=document.createElement("div");
box.className="ciclo";
box.innerHTML=`<h2>${c.nombre}</h2>`;

c.cursos.forEach(([nombre,req])=>{
total++;
const d=document.createElement("div");
d.className="curso";
d.textContent=nombre;
d.dataset.req=req.length?"Requisitos: "+req.join(", "):"Sin requisitos";

const desbloq=req.every(r=>aprobados.has(r));
if(desbloq)d.classList.add("disponible");
if(aprobados.has(nombre))d.classList.add("aprobado");

d.onclick=()=>{
if(!desbloq)return alert("Faltan: "+req.filter(r=>!aprobados.has(r)).join(", "));
aprobados.has(nombre)?aprobados.delete(nombre):aprobados.add(nombre);
localStorage.setItem("aprobados",JSON.stringify([...aprobados]));
render();
};

box.appendChild(d);
});
malla.appendChild(box);
});

barra.style.width=(aprobados.size/total*100)+"%";
}

reset.onclick=()=>{
if(confirm("¿Reiniciar malla?")){
aprobados.clear();
localStorage.clear();
render();
}
};

modo.onclick=()=>document.body.classList.toggle("oscuro");

render();
