const cursos = {
"Nivelación":{
"NIVELACION DE REDACCION":[],
"NIVELACION DE MATEMATICA":[]
},
"1er ciclo":{
"MATEMÁTICA I":["NIVELACION DE MATEMATICA"],
"INTRODUCCIÓN A LA VIDA UNIVERSITARIA":[],
"LABORATORIO DE QUÍMICA GENERAL":[],
"QUÍMICA GENERAL":[],
"INDIVIDUO Y MEDIO AMBIENTE":["NIVELACION DE REDACCION"],
"INGLÉS I":[],
"COMPRENSIÓN Y REDACCIÓN DE TEXTOS I":["NIVELACION DE REDACCION"]
},
"2do ciclo":{
"MATEMÁTICA II":["MATEMÁTICA I"],
"CIUDADANÍA Y REFLEXIÓN ÉTICA":[],
"INGLÉS II":["INGLÉS I"],
"COMPRENSIÓN Y REDACCIÓN DE TEXTOS II":["COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"],
"ESTADÍSTICA DESCRIPTIVA Y PROBABILIDADES":["MATEMÁTICA I"],
"PRINCIPIOS DE ALGORITMOS":[],
"DIBUJO PARA INGENIERÍA":["MATEMÁTICA I","INTRODUCCIÓN A LA VIDA UNIVERSITARIA"]
},
"3er ciclo":{
"LABORATORIO DE MECÁNICA CLÁSICA":["MATEMÁTICA II"],
"MECÁNICA CLÁSICA":["MATEMÁTICA II"],
"CÁLCULO I":["MATEMÁTICA II"],
"INVESTIGACIÓN ACADÉMICA":["INDIVIDUO Y MEDIO AMBIENTE","COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"],
"GEOLOGÍA":["DIBUJO PARA INGENIERÍA"],
"PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN":["DIBUJO PARA INGENIERÍA"],
"INGLÉS III":["INGLÉS II"],
"PROBLEMAS Y DESAFÍOS EN EL PERÚ ACTUAL":["INDIVIDUO Y MEDIO AMBIENTE","COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"]
},
"4to ciclo":{
"LABORATORIO DE MATERIALES DE CONSTRUCCIÓN":["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"],
"MATERIALES DE CONSTRUCCIÓN":["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"],
"FLUIDOS Y TERMODINÁMICA":["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"],
"LABORATORIO DE FLUIDOS Y TERMODINÁMICA":["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"],
"CÁLCULO II":["CÁLCULO I"],
"TOPOGRAFÍA - INGENIERIA CIVIL":["ESTADÍSTICA DESCRIPTIVA Y PROBABILIDADES","PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN"],
"ESTÁTICA":["MECÁNICA CLÁSICA","CÁLCULO I","LABORATORIO DE MECÁNICA CLÁSICA"],
"INGLÉS IV":["INGLÉS III"]
},
"5to ciclo":{
"CONSTRUCCIÓN":["MATERIALES DE CONSTRUCCIÓN","PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN"],
"FUNDAMENTOS DE DINÁMICA":["ESTÁTICA"],
"GEOMÁTICA":["GEOLOGÍA","TOPOGRAFÍA - INGENIERIA CIVIL"],
"TECNOLOGÍA DEL CONCRETO":["MATERIALES DE CONSTRUCCIÓN"],
"CÁLCULO AVANZADO PARA INGENIERÍA":["CÁLCULO II"],
"CALCULO PARA LA TOMA DE DECISIONES":["CÁLCULO II"],
"HERRAMIENTAS INFORMÁTICAS PARA LA TOMA DE DECISIONES":[]
},
"6to ciclo":{
"LABORATORIO DE ELASTICIDAD Y RESISTENCIA DE MATERIALES":["CÁLCULO AVANZADO PARA INGENIERÍA","CALCULO PARA LA TOMA DE DECISIONES","FUNDAMENTOS DE DINÁMICA"],
"ELASTICIDAD Y RESISTENCIA DE MATERIALES":["CÁLCULO AVANZADO PARA INGENIERÍA","CALCULO PARA LA TOMA DE DECISIONES","FUNDAMENTOS DE DINÁMICA"],
"LABORATORIO DE MECÁNICA DE FLUIDOS":["FUNDAMENTOS DE DINÁMICA"],
"MECÁNICA DE FLUIDOS":["FUNDAMENTOS DE DINÁMICA"],
"HERRAMIENTAS PARA LA COMUNICACIÓN EFECTIVA":["INVESTIGACIÓN ACADÉMICA"],
"CONSTRUCCIONES ESPECIALES":["CONSTRUCCIÓN"],
"MECÁNICA DE SUELOS":["GEOMÁTICA","FUNDAMENTOS DE DINÁMICA"],
"CURSO INTEGRADOR I - CIVIL":["TECNOLOGÍA DEL CONCRETO","CONSTRUCCIÓN","GEOMÁTICA"]
},
"7mo ciclo":{
"LABORATORIO DE HIDRÁULICA DE CANALES":["CURSO INTEGRADOR I - CIVIL","MECÁNICA DE FLUIDOS"],
"HIDRÁULICA DE CANALES":["CURSO INTEGRADOR I - CIVIL","MECÁNICA DE FLUIDOS"],
"INGENIERÍA GEOTÉCNICA":["CURSO INTEGRADOR I - CIVIL","MECÁNICA DE SUELOS"],
"MODELADO DE INFORMACIÓN DE EDIFICACIONES - BIM":["CONSTRUCCIONES ESPECIALES"],
"INGENIERÍA DE CARRETERAS":["MECÁNICA DE SUELOS","GEOMÁTICA"],
"INSTALACIONES EN EDIFICACIONES":["CONSTRUCCIONES ESPECIALES","MECÁNICA DE FLUIDOS"],
"ANÁLISIS ESTRUCTURAL I":["ELASTICIDAD Y RESISTENCIA DE MATERIALES","CURSO INTEGRADOR I - CIVIL"],
"FORMACIÓN PARA LA EMPLEABILIDAD":["HERRAMIENTAS PARA LA COMUNICACIÓN EFECTIVA"]
},
"8vo ciclo":{
"ANÁLISIS ESTRUCTURAL II":["ANÁLISIS ESTRUCTURAL I"],
"HIDROLOGÍA APLICADA":["HIDRÁULICA DE CANALES"],
"SEMINARIO DE INGENIERÍA CIVIL":["ANÁLISIS ESTRUCTURAL I","HIDRÁULICA DE CANALES","INGENIERÍA GEOTÉCNICA"],
"MECÁNICA DE SUELOS APLICADA":["INGENIERÍA GEOTÉCNICA"],
"ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA":["INSTALACIONES EN EDIFICACIONES"],
"ADMINISTRACIÓN Y ORGANIZACIÓN DE EMPRESAS CONSTRUCTORAS":["INSTALACIONES EN EDIFICACIONES","MODELADO DE INFORMACIÓN DE EDIFICACIONES - BIM"],
"CONSTRUCCIÓN DE CARRETERAS":["INGENIERÍA DE CARRETERAS"],
"ÉTICA PROFESIONAL":["HERRAMIENTAS INFORMÁTICAS PARA LA TOMA DE DECISIONES","FORMACIÓN PARA LA EMPLEABILIDAD"]
},
"9no ciclo":{
"GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN":["ADMINISTRACIÓN Y ORGANIZACIÓN DE EMPRESAS CONSTRUCTORAS","ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA"],
"INGENIERÍA DE CIMENTACIONES":["MECÁNICA DE SUELOS APLICADA"],
"PAVIMENTOS":["CONSTRUCCIÓN DE CARRETERAS","MECÁNICA DE SUELOS APLICADA"],
"INGENIERÍA DE LOS RECURSOS HIDRÁULICOS":["HIDROLOGÍA APLICADA"],
"SISTEMA INTEGRADO DE GESTIÓN EN LA CONSTRUCCIÓN":["ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA"],
"FORMACIÓN PARA LA INVESTIGACIÓN - CIVIL":["SEMINARIO DE INGENIERÍA CIVIL"],
"CONCRETO ARMADO":["ANÁLISIS ESTRUCTURAL II"]
},
"10mo ciclo":{
"INGENIERIA SISMORRESISTENTE":["CONCRETO ARMADO","INGENIERÍA DE CIMENTACIONES"],
"GESTIÓN DE PROYECTOS DE INVERSIÓN PÚBLICA":["GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"],
"TALLER DE INVESTIGACIÓN - CIVIL":["FORMACIÓN PARA LA INVESTIGACIÓN - CIVIL"],
"CURSO INTEGRADOR II - CIVIL":["CURSO INTEGRADOR I - CIVIL","INGENIERÍA DE CIMENTACIONES","GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"],
"FUNDAMENTOS DE METODOLOGÍA VDC EN EDIFICACIONES":["MODELADO DE INFORMACIÓN DE EDIFICACIONES - BIM","GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"],
"SEGURIDAD Y SALUD OCUPACIONAL EN OBRAS DE CONSTRUCCIÓN":["SISTEMA INTEGRADO DE GESTIÓN EN LA CONSTRUCCIÓN","GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN"],
"SOSTENIBILIDAD AMBIENTAL EN LA CONSTRUCCIÓN":["HIDROLOGÍA APLICADA"],
"ANÁLISIS DE ESTRUCTURAS POR ELEMENTOS FINITOS":["CONCRETO ARMADO"],
"MÉTODOS NUMÉRICOS":["CÁLCULO AVANZADO PARA INGENIERÍA"],
"ELEMENTARY BUSINESS ENGLISH":["INGLÉS IV"]
}
};

let aprobados = JSON.parse(localStorage.getItem("aprobados")) || [];
const malla = document.getElementById("malla");
const mensaje = document.getElementById("mensaje");

function requisitosOk(reqs){
    return reqs.every(r => aprobados.includes(r));
}

function render(){
    malla.innerHTML = "";
    for(const ciclo in cursos){
        const div = document.createElement("div");
        div.className = "ciclo";
        div.innerHTML = `<h2>${ciclo}</h2>`;
        for(const ramo in cursos[ciclo]){
            const reqs = cursos[ciclo][ramo];
            const r = document.createElement("div");
            r.className = "ramo";
            if(aprobados.includes(ramo)) r.classList.add("aprobado");
            else if(requisitosOk(reqs)) r.classList.add("desbloqueado");
            else r.classList.add("bloqueado");
            r.textContent = ramo;
            r.onclick = () => {
                if(aprobados.includes(ramo)) return;
                if(!requisitosOk(reqs)){
                    const faltan = reqs.filter(x => !aprobados.includes(x));
                    mensaje.textContent = "Faltan aprobar:\n• " + faltan.join("\n• ");
                    mensaje.classList.remove("oculto");
                    setTimeout(()=>mensaje.classList.add("oculto"),4000);
                    return;
                }
                aprobados.push(ramo);
                localStorage.setItem("aprobados",JSON.stringify(aprobados));
                render();
            };
            div.appendChild(r);
        }
        malla.appendChild(div);
    }
}

document.getElementById("reset").onclick = () => {
    if(confirm("¿Seguro que deseas reiniciar toda la malla?")){
        localStorage.removeItem("aprobados");
        aprobados = [];
        render();
    }
};

render();
